### ISSUE TITLE
Include end day in calculations

### ISSUE THREAD

**Issue by jedidiahkkh** [szenius/notion-burndown#8]
Currently runs from beginning of 1st day to beginning of last day. This means the last day is not counted, e.g. if we run with a sprint from 1 - 7 June (7 days) we have `numDaysInSprint=6`. When calculating days of work to generate the constant line, we subtract one from this number, meaning the burndown only has 5 days of work, losing 2 days overall.

**Comment by jedidiahkkh** [comment]
This assumes a practice where users put the end date of one sprint the day before the start date of the next sprint e.g.
Sprint 1: 1 - 14 June
Sprint 2: 15 - 28 June
etc...

**Comment by szenius** [comment]
Should be fixed in https://github.com/szenius/notion-burndown/commit/b2c752d9493418a8a4bd7e1d3ded82f80bfa31ea

For start/end of sprint specifically, can refer to issue #6
